name: onpush

on:
  push:

env:
  PYTHON_VERSION: 3.8.9
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: |
          git lfs checkout
      - name: install-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install poetry
        run: |
          pip install poetry==1.2.1
          poetry config virtualenvs.in-project true
      - name: install dependencies
        if: steps.load-cached.outputs.cache-hit != 'true'

        run: poetry install

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
